### ISSUE TITLE
gens 2 lines together in the encoder / decoder code

### ISSUE THREAD

**Issue by joeblew99** [goadesign/plugins#2] opened 2017-09-13 14:06 UTC
This is the correct code:

https://github.com/goadesign/plugins/blob/e52847812efc3ff17e48896978e2c536048f3663/goakit/examples/cellar/gen/http/storage/client/encode_decode.go#L75

However, when i run this myself i get errors when two lines are generated as one:

Here is one of the offending functions with bold for the error:
````
// BuildShowRequest instantiates a HTTP request object with method and path set
// to call the storage show endpoint.
func (c *Client) BuildShowRequest(v interface{}) (*http.Request, error) {
	p, ok := v.(*storage.ShowPayload)
	if !ok {
		return nil, goahttp.ErrInvalidType("storage", "show", "*storage.ShowPayload", v)
	}
	**var id stringid = p.ID**
	u := &url.URL{Scheme: c.scheme, Host: c.host, Path: ShowStoragePath(id)}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, goahttp.ErrInvalidURL("storage", "show", u.String(), err)
	}

	return req, nil
}
````

The error occurs in 6 places as part of the encoder / decoder.
````

cd /Users/apple/workspace/go/src/github.com/gedw99/gitty/exp/services/gokit/cell/cmd/cellarcli && go run main.go
# github.com/gedw99/gitty/exp/services/gokit/cell/gen/http/sommelier/client
../../gen/http/sommelier/client/encode_decode.go:23:11: undefined: v
../../gen/http/sommelier/client/encode_decode.go:25:82: undefined: v
# github.com/gedw99/gitty/exp/services/gokit/cell/gen/http/storage/client
../../gen/http/storage/client/encode_decode.go:75:9: undefined: stringid
../../gen/http/storage/client/encode_decode.go:135:11: undefined: v
../../gen/http/storage/client/encode_decode.go:137:75: undefined: v
../../gen/http/storage/client/encode_decode.go:207:9: undefined: stringid
make: *** [run] Error 2

````

make file to repo:

````
# ref: goa and gokit

# https://github.com/goadesign/goa/tree/v2

DIR=${PWD}

GOA_GO_PATH=goa.design/goa
GOA_FILE_PATH=${GOPATH}/src/${GOA_GO_PATH}

GOAPLUG_GO_PATH=goa.design/plugins
GOAPLUG_FILE_PATH=${GOPATH}/src/${GOAPLUG_GO_PATH}

EX_GO_PATH=goa.design/plugins/goakit/examples/cellar/design
EX_FILE_PATH=${GOPATH}/src/${EX_GO_PATH}

EX_ALIAS_PATH=${DIR}/cell




check:

	@echo "## Checking paths"
	@echo "DIR \t \t ${DIR}"
	@echo 

	@echo "GOA_GO_PATH: \t ${GOA_GO_PATH}"
	@echo "GOA_FILE_PATH: \t ${GOA_FILE_PATH}"
	@echo 

	@echo "GOAPLUG_GO_PATH: \t ${GOAPLUG_GO_PATH}"
	@echo "GOAPLUG_FILE_PATH: \t ${GOAPLUG_FILE_PATH}"
	@echo 

	@echo "EX_GO_PATH: \t ${EX_GO_PATH}"
	@echo "EX_FILE_PATH: \t ${EX_FILE_PATH}"
	@echo 

	@echo "EX_ALIAS_PATH: \t ${EX_ALIAS_PATH}"
	@echo 





dep:

	# goa v2
	go get -u ${GOA_GO_PATH}/...
	cd ${GOA_FILE_PATH}/cmd/goa && go install

	# check goa tools are there
	goa version

	# get gokit plugin and examples
	go get -u ${GOAPLUG_GO_PATH}/...


dep-clean:

	# delete ex code
	rm -rf ${GOA_FILE_PATH}
	rm -rf ${GOAPLUG_FILE_PATH}




gen:

	# Now try the cellar example
	# ref: https://github.com/goadesign/plugins/tree/master/goakit/examples/cellar
	mkdir ${EX_ALIAS_PATH}
	cd ${EX_ALIAS_PATH} && goa gen ${EX_GO_PATH}
	cd ${EX_ALIAS_PATH} && goa example ${EX_GO_PATH}

gen-clean:

	# delete generated code
	rm -rf ${EX_ALIAS_PATH} 




open-bash:

	# open bash terminal
	open -a Terminal.app ${EX_ALIAS_PATH}

open-fs:

	# Opens Finder.
	open ${EX_ALIAS_PATH}

open-vsc:

	# Opens Visual Studio Code
	code ${EX_ALIAS_PATH}

open-vs:

	# Opens Visual Studio for Mac
	open ${EX_ALIAS_PATH}

	# Works and runs :)


run:
	cd ${EX_ALIAS_PATH}/cmd/cellarcli && go run main.go

build:
	cd ${EX_ALIAS_PATH}/cmd/cellarcli && go build



````

**Comment by nitinmohan87** [comment] 2018-01-03 20:52
@joeblew99 Thanks for reporting this issue. I am not able to reproduce this right now with the latest goa v2 package. Could you please try again with the most recent goa v2 code and see if your issue still persists?

**Comment by gedw99** [comment] 2018-01-08 08:32
Thanks for having a look.

SO its broken still for me at even the go get level:

````
go get -u goa.design/plugins/...
package goa.design/plugins/goakit/examples/fetcher/archiver/cmd/archivercli
        imports goa.design/plugins/goakit/examples/client/archiver/gen/http/cli: cannot find package "goa.design/plugins/goakit/examples/client/archiver/gen/http/cli" in any of:
        /usr/local/opt/go/libexec/src/goa.design/plugins/goakit/examples/client/archiver/gen/http/cli (from $GOROOT)
        /Users/apple/workspace/go/src/goa.design/plugins/goakit/examples/client/archiver/gen/http/cli (from $GOPATH)
make: *** [dep] Error 1

```

**Comment by raphael** [comment] 2018-02-19 17:43
Closing this issue as I'm not able to repro either problem.

**Closed by raphael** 2018-02-19 17:43 UTC
